version: '3.7'

services:
  ratemycourse_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: 'npm run dev'
    volumes:
      - ./src:/usr/app/src
    stdin_open: true
    restart: on-failure
